apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-app-deployer
  namespace: cloudserve
rules:
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups: [""]
    resources:
      - services
      - configmaps
      - secrets
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-app-deployer-binding
  namespace: cloudserve
subjects:
  - kind: ServiceAccount
    name: default
    namespace: jenkins # 👈 Jenkins lives here
roleRef:
  kind: Role
  name: jenkins-app-deployer
  apiGroup: rbac.authorization.k8s.io
