apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-app-deployer-binding
  namespace: cloudserve
subjects:
  - kind: ServiceAccount
    name: jenkins-agent
    namespace: cloudserve
roleRef:
  kind: Role
  name: jenkins-app-deployer
  apiGroup: rbac.authorization.k8s.io
